networks:
  default:
    external: true
    name: ks101

services:

  stream:
    image: ksd_streams:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    # provides network privileges to allow 'tc' to be used
    cap_add:
      - NET_ADMIN
    volumes:
      - ./streams.properties:/streams.properties
      - ./scripts:/scripts
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      CLIENT_ID_PREFIX: "stream"
