networks:
  default:
    external: true
    name: ks101

services:
  
  admin:
    image: ks101_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-clients.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    volumes:
      - ./admin-1.0.tar:/app.tar
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092

  producer:
    image: ks101_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-clients.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    volumes:
      - ./producer-1.0.tar:/app.tar
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092

  streams:
    image: ks101_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-streams.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    volumes:
      - ./streams-1.0.tar:/app.tar
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092

  consumer:
    image: ks101_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-clients.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    volumes:
      - ./consumer-1.0.tar:/app.tar
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092

  nginx:
    image: nginx:latest
    container_name: ks101a-nginx
    hostname: nginx
    stop_grace_period: 30s
    healthcheck:
      test: curl -s http://localhost:80 || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '8081:8081'
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
